/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_onem2m_abstdev_impl_TempAndRHImpl */

#ifndef _Included_org_onem2m_abstdev_impl_TempAndRHImpl
#define _Included_org_onem2m_abstdev_impl_TempAndRHImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_onem2m_abstdev_impl_TempAndRHImpl
 * Method:    getTempNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_onem2m_abstdev_impl_TempAndRHImpl_getTempNative
  (JNIEnv *, jobject);

/*
 * Class:     org_onem2m_abstdev_impl_TempAndRHImpl
 * Method:    getRHNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_onem2m_abstdev_impl_TempAndRHImpl_getRHNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
