target:
	javac ./org/onem2m/abstdev/*.java -d ../bin
	javac ./org/onem2m/abstdev/constant/*.java -d ../bin
	javac ./serial/*.java -d ../bin
	javac ./org/onem2m/abstdev/impl/*.java -d ../bin
	javac ./org/onem2m/abstdev/client/*.java -d ../bin
clean:
	rm -rf ../bin/org